# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.achievement-service:
        class:  AppBundle\Service\AchievementService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            repositoryName: "AppBundle:Achievement"
    app.answer-service:
        class:  AppBundle\Service\AnswerService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            repositoryName: "AppBundle:Answer"
    app.game-service:
        class:  AppBundle\Service\GameService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    app.scene-service:
        class:  AppBundle\Service\SceneService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            repositoryName: "AppBundle:Scene"
#    manager_name:
#        class: AppBundle\Manager\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.launch-manager:
        class:  AppBundle\Manager\LaunchManager
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    app.game-manager:
        class:  AppBundle\Manager\GameManager
        arguments:
            achievementService: "@app.achievement-service"
            answerService: "@app.answer-service"
            gameService: "@app.game-service"
    app.flash_messenger:
        class: AppBundle\Messenger\Flash
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}


    admin.achievements:
        class: AppBundle\Admin\AchievementAdmin
        arguments: [~, AppBundle\Entity\Achievement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: txt.achievements}
        calls:
            - [setTranslationDomain, ['AdminBundle']]
    admin.characteristics:
        class: AppBundle\Admin\CharacteristicAdmin
        arguments: [~, AppBundle\Entity\Characteristic, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: txt.characteristics}
        calls:
            - [setTranslationDomain, ['AdminBundle']]
    admin.scenes:
        class: AppBundle\Admin\SceneAdmin
        arguments:
            - null
            - AppBundle\Entity\Scene
            - AppBundle:Admin
        tags:
            - { name: sonata.admin, manager_type: orm, label: txt.scenes}
        calls:
            - [setTranslationDomain, ['AdminBundle']]
    admin.sentences:
        class: AppBundle\Admin\SentenceAdmin
        arguments:
            - null
            - AppBundle\Entity\Sentence
            - AppBundle:Admin
        tags:
            - { name: sonata.admin, manager_type: orm, label: txt.sentences}
        calls:
            - [setTranslationDomain, ['AdminBundle']]
