# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.game-service:
        class:  AppBundle\Service\GameService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
#    manager_name:
#        class: AppBundle\Manager\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.launch-manager:
        class:  AppBundle\Manager\LaunchManager
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    app.game-manager:
        class:  AppBundle\Manager\GameManager
        arguments:
            gameService: "@app.game-service"
